const option = (
  id,
  text,
  assessment,
  chanceDelta,
  capabilityDeltas,
  consequence,
  didWell,
  improve,
  betterMove,
  mentalModel,
  extra = {},
) => ({
  id,
  text,
  assessment,
  chanceDelta,
  capabilityDeltas,
  feedback: {
    assessment,
    consequence,
    didWell,
    improve,
    betterMove,
    mentalModel,
  },
  ...extra,
});

export const PHASES = [
  { id: 1, title: "Learn the system", range: [1, 4] },
  { id: 2, title: "Frame the work", range: [5, 9] },
  { id: 3, title: "Build safe AI", range: [10, 13] },
  { id: 4, title: "Deliver real adoption", range: [14, 16] },
  { id: 5, title: "Earn trust & ownership", range: [17, 18] },
];

export const STAGES = [
  {
    id: 1,
    phase: "Learn the system",
    timeline: "Day 1 · 9:30 AM",
    title: "The blank-page brief",
    speaker: "Maya · Assistant Manager",
    manager: "Maya",
    scenario:
      "Maya welcomes you to the Automation CoE and says, “We need you to get up to speed on the agency assistant quickly. Start with the knowledge base and come back when you understand the project.” The shared drive contains hundreds of files, nobody has given you a reading order, and your first team check-in is tomorrow afternoon.",
    question: "What do you do first?",
    hint:
      "Your first job is not to know everything. Clarify the outcome, boundaries, people, and evidence that should guide the first investigation.",
    source: "First Two Weeks 80/20 Onboarding",
    options: [
      option(
        "A",
        "Clarify the expected first-week outcome, scope and guardrails; identify the key people and documents; send Maya a short investigation plan.",
        "Strong judgment",
        6,
        { reliability: 5, analysis: 4, ownership: 5 },
        "Maya confirms the priority documents and introduces you to the agency SME. Your plan becomes tomorrow’s check-in agenda.",
        "You showed initiative without pretending to know the domain, and you made your learning visible.",
        "Keep the first plan lightweight. A new joiner can over-engineer an onboarding process before learning the team’s rhythm.",
        "Use a one-page plan: outcome, scope, people, evidence, open questions, and tomorrow’s checkpoint.",
        "People–Problem–Position: learn the decision network and core problem before trying to absorb every detail.",
      ),
      option(
        "B",
        "Read every document in the shared drive tonight, then give Maya a detailed summary tomorrow.",
        "Hard-working but unfocused",
        -1,
        { reliability: 2, analysis: -3, ownership: 1 },
        "You work late but still cannot tell which documents are current or which decisions matter. Maya asks why you did not clarify the priority.",
        "Your effort and willingness to learn are positive signals.",
        "Volume is not the same as direction. You risk becoming informed about history but unclear about the current decision.",
        "Ask which outcome the reading must support, then prioritize decision logs, current metrics, recent failures, and named sources of truth.",
        "The first 20% is People, Problem, and Position. The remaining knowledge becomes easier to prioritize afterward.",
      ),
      option(
        "C",
        "Wait for Maya to provide a detailed onboarding checklist because you do not want to make assumptions.",
        "Too passive",
        -5,
        { reliability: -3, ownership: -6 },
        "At the next check-in, you have no questions, map, or useful artifact. Maya now expects to supervise your learning more closely.",
        "You correctly recognized that assumptions should not be treated as facts.",
        "Avoiding all assumptions prevents progress. Good BAs form explicit hypotheses and ask for correction.",
        "Draft a small investigation plan, label unknowns, and ask Maya to correct the priority rather than creating the plan for you.",
        "Ownership means moving ambiguity toward clarity while escalating only the decisions outside your authority.",
      ),
      option(
        "D",
        "Tell the team you already understand chatbots from your previous work and immediately propose a new platform architecture.",
        "Premature solutioning",
        -7,
        { collaboration: -5, analysis: -5, risk: -2 },
        "The developers notice that your proposal ignores current systems and controls. Your confidence reads as poor listening.",
        "You brought relevant experience and energy into the room.",
        "You used prior experience as an answer before understanding the local problem, dependencies, or decision rights.",
        "Offer your experience as a hypothesis after mapping the current workflow and asking where the team sees the largest gap.",
        "Keep your identity small: expertise should improve your questions, not lock you into an early solution.",
      ),
    ],
  },
  {
    id: 2,
    phase: "Learn the system",
    timeline: "Day 3 · 3:00 PM",
    title: "The invisible org chart",
    speaker: "Ken · Senior BA",
    manager: "Maya",
    scenario:
      "Ken gives you an organization chart and warns that it does not show how work actually moves. Andrea owns product direction, Vincent understands agent workflows, Grace can stop unsafe releases, and Ravi’s technical estimate often changes the feasible scope. Maya asks you to prepare a stakeholder map for the next chatbot enhancement.",
    question: "How will you map the stakeholders?",
    hint:
      "Map people by their role in this specific decision: who decides, who knows, and who can stop or unblock the work.",
    source: "Stakeholder Role Map for a New Team",
    options: [
      option(
        "A",
        "Map decision makers, SMEs and blockers by topic, record evidence of their influence, and treat the map as a weekly hypothesis.",
        "Strong judgment",
        6,
        { analysis: 4, collaboration: 5, ownership: 3 },
        "Your map reveals that Grace is a release gatekeeper while Vincent is the source of frontline workflow truth. Maya uses it to sequence interviews.",
        "You separated formal title from actual decision, knowledge, and control power.",
        "Do not let the labels become political judgments or permanent identities.",
        "Add what each person protects, what evidence they hold, and when their input is needed; revise after real decisions.",
        "A stakeholder map is a map of influence and evidence, not a contact list or ranking of importance.",
      ),
      option(
        "B",
        "Copy reporting lines into a RACI and send it out for everyone to approve.",
        "Useful artifact, incomplete model",
        1,
        { reliability: 2, analysis: -1 },
        "The RACI clarifies formal roles but misses Ravi’s technical influence and Grace’s control gate. Late surprises remain possible.",
        "You created a shared artifact and attempted to make responsibility explicit.",
        "Formal accountability alone does not show information power, trust, incentives, or issue-specific blockers.",
        "Keep the RACI, then add decision, SME, blocker, influence, evidence, and engagement timing fields.",
        "Roles are contextual. The same person can advise one decision and block another.",
      ),
      option(
        "C",
        "Prioritize only Andrea and Maya because senior leaders decide whether your contract converts.",
        "Politically narrow",
        -5,
        { collaboration: -6, analysis: -3, reliability: -1 },
        "You miss frontline exceptions and a compliance dependency. The team senses that you are managing upward rather than learning the system.",
        "You recognized that decision authority and manager expectations matter.",
        "Over-focusing on seniority leaves you blind to operational truth and necessary control approval.",
        "Understand senior success criteria while building trust with SMEs, delivery partners, and gatekeepers.",
        "Formal power, information power, and trust influence are different—and all can change the outcome.",
      ),
      option(
        "D",
        "Treat Grace as an obstacle and involve Compliance only when the design is nearly finished.",
        "High-risk stakeholder error",
        -8,
        { risk: -8, collaboration: -6 },
        "Grace identifies a privacy issue late, forcing redesign. Maya says the delay was avoidable.",
        "You tried to protect delivery speed and reduce meeting overhead.",
        "A blocker usually protects a real constraint. Late involvement converts a manageable design input into a release stop.",
        "Ask what Grace must protect and bring her into the earliest decision where the control could change scope.",
        "Do not fight the gate. Understand the protected risk early enough to design with it.",
      ),
    ],
  },
  {
    id: 3,
    phase: "Learn the system",
    timeline: "End of week 1",
    title: "Three versions of the truth",
    speaker: "Maya · Assistant Manager",
    manager: "Maya",
    scenario:
      "Your first interviews produce conflicting stories. Andrea says the team needs faster delivery, Vincent says agents do not trust the assistant, and Ravi says unclear acceptance criteria cause rework. Maya asks for your diagnosis, but you have only one week of context and limited metrics.",
    question: "What do you present?",
    hint:
      "Compress the evidence into Challenge, Goal, and Gap—but label observation, inference, and assumption separately.",
    source: "Three-Question Organizational Diagnosis",
    options: [
      option(
        "A",
        "Present a provisional Challenge–Goal–Gap chain, show conflicting evidence and unknowns, and propose two small checks before committing to a diagnosis.",
        "Strong judgment",
        6,
        { analysis: 6, reliability: 3, ownership: 3 },
        "Maya corrects one assumption and approves two checks: failed-query review and an agent workflow observation.",
        "You synthesized information without turning a first-week hypothesis into false certainty.",
        "Make sure the proposed checks can change a decision; avoid research that only adds background.",
        "Write: because [challenge], the team aims to [observable goal], but lacks [gap]. Then name the evidence needed to confirm it.",
        "A diagnosis links challenge, goal, and gap causally. It is stronger than a list of complaints.",
      ),
      option(
        "B",
        "Choose Andrea’s explanation because she owns product direction and frame faster delivery as the team’s core problem.",
        "Authority-weighted shortcut",
        -3,
        { analysis: -4, collaboration: -2 },
        "Your summary sounds aligned upward but fails to explain low trust or rework. Maya asks you to speak to delivery and users again.",
        "You respected product accountability and tried to create a clear focus.",
        "Seniority is not evidence. One stakeholder’s goal may describe the symptom rather than the root gap.",
        "Compare the three accounts, ask what evidence supports each, and identify which decision changes if one is true.",
        "Cross-check decision makers, SMEs, and blockers rather than treating one power center as the whole system.",
      ),
      option(
        "C",
        "List all three viewpoints without interpreting them so nobody feels misrepresented.",
        "Accurate collection, weak synthesis",
        0,
        { collaboration: 2, ownership: -3, analysis: -2 },
        "Everyone agrees the notes are accurate, but no next decision becomes clearer. Maya asks for your recommendation.",
        "You listened carefully and preserved competing viewpoints.",
        "A BA adds value by turning inputs into a testable model and next decision, not only by recording them.",
        "Separate fact from interpretation, propose the most plausible causal chain, and invite correction.",
        "Alignment is not the absence of disagreement. It is enough shared reasoning to make and carry out a decision.",
      ),
      option(
        "D",
        "Promise to redesign the delivery process immediately because rework is the most actionable issue.",
        "Premature commitment",
        -6,
        { ownership: -2, analysis: -6, reliability: -3 },
        "The proposal grows quickly, but later evidence shows that outdated content is driving many failures. Your early promise becomes a credibility cost.",
        "You looked for an actionable contribution rather than hiding behind analysis.",
        "Actionability does not make an unverified diagnosis correct, and the scope is too large for a first-week hypothesis.",
        "Validate the suspected gap with a small reversible artifact before promising a process redesign.",
        "Use small contributions to test your role hypothesis before committing the team to a major solution.",
      ),
    ],
  },
  {
    id: 4,
    phase: "Learn the system",
    timeline: "Week 2 · Field visit",
    title: "The SOP says otherwise",
    speaker: "Vincent · Agency Operations SME",
    manager: "Maya",
    scenario:
      "During an agency visit, two experienced agents show you shortcuts that contradict the official SOP. They keep personal notes because the approved process is slow and the chatbot misses mixed Cantonese-English questions. Vincent says, “Those are just bad habits; use the documented process for requirements.”",
    question: "How do you respond?",
    hint:
      "The SOP describes intended work. The AS-IS model needs evidence from real cases, including handoffs, exceptions, controls, and workarounds.",
    source: "Business Analysis Delivery Lifecycle",
    options: [
      option(
        "A",
        "Observe two or three recent cases, map the documented and actual flows, identify why workarounds exist, and validate control risks with Vincent.",
        "Strong judgment",
        6,
        { analysis: 6, collaboration: 4, risk: 3 },
        "You discover that a slow approval handoff creates the workaround and that mixed-language retrieval is a separate quality gap.",
        "You treated frontline behavior as evidence without assuming every workaround should become the target process.",
        "Protect privacy when reviewing real cases and avoid normalizing unsafe shortcuts.",
        "Map trigger, steps, handoffs, decisions, exceptions, controls, outputs, and workarounds; then distinguish symptom from root cause.",
        "SOP is the intended process. AS-IS must be validated against real work.",
      ),
      option(
        "B",
        "Follow the official SOP only because regulated processes should never document non-compliant behavior.",
        "Control-minded but incomplete",
        -2,
        { risk: 3, analysis: -5, collaboration: -2 },
        "Your requirements reproduce the official flow but fail to solve the delay that drives agents around it.",
        "You respected that controls and approved procedures matter in insurance.",
        "Hiding actual behavior does not reduce risk; it prevents the team from addressing why the behavior exists.",
        "Document the real workflow safely, label control breaches clearly, and design a compliant target state that removes the incentive for the workaround.",
        "A useful AS-IS model includes uncomfortable reality. A TO-BE model decides what must change.",
      ),
      option(
        "C",
        "Add every agent shortcut to the backlog because users know the workflow better than headquarters.",
        "User-centered but unsafe",
        -5,
        { collaboration: 2, risk: -7, analysis: -2 },
        "Grace flags several requests as privacy or conduct risks. The agents feel heard, but the backlog is not buildable or governable.",
        "You valued frontline evidence and the practical cost of workflow friction.",
        "User behavior explains needs; it does not automatically define safe requirements.",
        "Translate each workaround into an underlying need, constraint, and candidate controlled solution.",
        "Separate need, requirement, constraint, preference, and assumption before prioritization.",
      ),
      option(
        "D",
        "Tell Vincent the agents proved the SOP is wrong and ask him to rewrite it before you continue.",
        "Confrontational diagnosis",
        -4,
        { collaboration: -6, ownership: -2 },
        "Vincent becomes defensive and the observation work stalls. You lose access to the SME who can explain the process history.",
        "You recognized a real gap between documented and actual work.",
        "You framed the evidence as blame and demanded a solution outside your role before understanding the constraints.",
        "Use neutral language: “I observed this pattern; what pressure or exception is the current workaround handling?”",
        "Challenge the process without attacking the person who owns or explains it.",
      ),
    ],
  },
  {
    id: 5,
    phase: "Frame the work",
    timeline: "Week 3 · Intake meeting",
    title: "Make it smarter",
    speaker: "Elaine · Business Unit Stakeholder",
    manager: "Maya",
    scenario:
      "Elaine asks the team to “make the agent chatbot smarter” before a large agency event. She wants more topics, faster answers, personal performance data, and fewer escalations, all within six weeks. Ravi asks you what should enter refinement, while Andrea wants a recommendation tomorrow.",
    question: "What is your next move?",
    hint:
      "Before decomposing features, define the problem, observable win, and constraints. “Smarter” is not a testable outcome.",
    source: "Problem Win Constraint Workflow",
    options: [
      option(
        "A",
        "Run a short Problem–Win–Constraint intake, define the user and decision, baseline the pain, then recommend a bounded six-week outcome.",
        "Strong judgment",
        7,
        { analysis: 6, ownership: 5, impact: 4 },
        "The team agrees to improve resolution for the top approved enquiry types while excluding personal data from this release.",
        "You converted a broad solution request into a buildable decision with a measurable win.",
        "Do not turn the intake into a long discovery phase; the event creates a real time constraint.",
        "State the problem, win metric, non-negotiable controls, deadline, and the smallest scope that can produce useful learning.",
        "Problem–Win–Constraint comes before decomposition. Otherwise the backlog becomes a container for unrelated wishes.",
      ),
      option(
        "B",
        "Create four epics—topics, latency, performance data, escalation—and ask the team to estimate everything.",
        "Organized but premature",
        -2,
        { reliability: 2, analysis: -5, impact: -2 },
        "The estimation workshop exposes hidden dependencies but consumes a day without clarifying which outcome matters most.",
        "You translated vague themes into work areas and involved delivery partners early.",
        "You decomposed before agreeing on the problem, win, and constraints, so effort estimates cannot guide priority well.",
        "Frame the outcome first, then estimate only the options that could plausibly deliver it.",
        "Good decomposition cannot rescue an unclear decision frame.",
      ),
      option(
        "C",
        "Ask Elaine to rank her four requests and treat the top two as the MVP.",
        "Fast but stakeholder-dependent",
        0,
        { collaboration: 2, ownership: -3, risk: -1 },
        "Elaine ranks personal performance first, but IT and Compliance cannot support it within six weeks.",
        "You sought a priority decision from the business owner instead of accepting everything.",
        "Preference ranking ignores feasibility, control constraints, evidence, and the outcome behind the request.",
        "Ask Elaine what result the event must create, then present feasible options with value, risk, and dependency trade-offs.",
        "Stakeholders own outcomes; product judgment turns requests into viable options and recommendations.",
      ),
      option(
        "D",
        "Promise the complete request to demonstrate that the new BA can deliver under pressure.",
        "Overcommitment",
        -8,
        { reliability: -7, risk: -4, ownership: -2 },
        "The team immediately identifies unresolved access, privacy, and data dependencies. Maya must reset expectations for you.",
        "You showed urgency and a desire to build trust through delivery.",
        "A promise made before feasibility and control checks creates the surprise that reliable teams avoid.",
        "Give a high-confidence bounded commitment and a lower-confidence expansion path instead of promising the full wish list.",
        "Reliability is not saying yes quickly. It is making commitments the team can honor without hidden risk.",
      ),
    ],
  },
  {
    id: 6,
    phase: "Frame the work",
    timeline: "Week 4 · Business review",
    title: "The senior stakeholder’s idea",
    speaker: "Elaine · Business Unit Stakeholder",
    manager: "Andrea",
    scenario:
      "Elaine proposes sending proactive chatbot prompts to agents who performed poorly in a product category. She wants a yes-or-no answer in the meeting. You do not yet have a better solution, but you suspect that recent category performance may not represent intent and that a poorly timed prompt could reduce trust.",
    question: "How do you answer in the room?",
    hint:
      "You do not need a superior idea. Separate the proposed solution from the outcome, surface assumptions, and offer a controlled next step.",
    source: "How to Respond When BU Has the Idea",
    options: [
      option(
        "A",
        "Say yes to a bounded test—not to settled strategy—then define hypothesis, segment, success metric, guardrail, and review date.",
        "Strong product judgment",
        7,
        { ownership: 6, analysis: 5, collaboration: 3, impact: 4 },
        "Elaine keeps momentum, and Andrea sees that you protected learning quality without blocking the idea.",
        "You converted opinion into a reversible experiment and kept the stakeholder’s outcome at the center.",
        "Be explicit about what evidence would make the team stop, refine, or scale the test.",
        "Close with the exact v1 rule, owner, metric, guardrail, and review decision.",
        "Conditional yes: test under defined conditions, but do not treat the solution as proven strategy.",
      ),
      option(
        "B",
        "Approve the idea because the business owns the outcome and can judge agent behavior better than the project team.",
        "Collaborative but uncritical",
        -4,
        { collaboration: 1, ownership: -5, analysis: -4 },
        "The campaign launches without guardrails and later generates complaints from agents who felt unfairly targeted.",
        "You respected business context and avoided reflexively rejecting a stakeholder proposal.",
        "Business ownership does not remove the team’s responsibility to expose assumptions, user harm, and measurement quality.",
        "Support a bounded test only after defining what the signal means and what negative outcome stops the experiment.",
        "Stakeholder alignment is not passive agreement. It is shared commitment to a decision and its evidence.",
      ),
      option(
        "C",
        "Reject the idea until you can design a better personalization model.",
        "Protective but blocking",
        -2,
        { risk: 2, collaboration: -4, ownership: -2 },
        "You prevent an unbounded launch, but Elaine sees the team as theoretical and slow. No learning plan replaces the proposal.",
        "You noticed weak assumptions and protected users from an untested broad rollout.",
        "Rejection without a safer next move gives up momentum and does not improve the evidence.",
        "Offer a small reversible test or an evidence-gathering step with clear decision criteria.",
        "Product judgment is not having the best idea on demand. It is choosing the safest useful next move.",
      ),
      option(
        "D",
        "Ask for more data and postpone the discussion without defining which decision the data should support.",
        "Analysis without decision",
        -3,
        { analysis: -2, ownership: -5, reliability: -1 },
        "The request returns in two weeks with more spreadsheets but the same unresolved assumptions.",
        "You resisted making a decision with insufficient evidence.",
        "“More data” is not an investigation plan. It can delay ownership indefinitely.",
        "Name the uncertainty, the minimum evidence needed, the decision threshold, and when the team will decide.",
        "Write the decision before the questions so research has an endpoint.",
      ),
    ],
  },
  {
    id: 7,
    phase: "Frame the work",
    timeline: "Month 2 · Discovery workshop",
    title: "Questions that go nowhere",
    speaker: "Vincent · Agency Operations SME",
    manager: "Maya",
    scenario:
      "A workshop is drifting. Team members keep asking Vincent broad questions such as “What do agents need?” He responds with long stories, but the team still cannot decide whether the next release should prioritize product knowledge, claim status, or performance enquiries. You are asked to take over the questioning.",
    question: "How do you reset the discussion?",
    hint:
      "State the decision first. Then use context, observation, impact, and a focused question; probe with examples and close the loop.",
    source: "Senior BA Questioning and Probing",
    options: [
      option(
        "A",
        "State the scope decision, summarize current evidence, ask which workflow causes the highest avoidable cost, probe a recent case, and confirm the implication.",
        "Strong facilitation",
        6,
        { analysis: 5, collaboration: 5, ownership: 4 },
        "Vincent describes a recurring claim-status journey with measurable handling time. The team leaves with a decision and evidence gap.",
        "Your questions had a clear decision destination and invited concrete operational evidence.",
        "Avoid leading Vincent toward the answer you already prefer.",
        "Use neutral language and close with: “So for this release, are we agreeing X because Y, pending Z evidence?”",
        "Context → observation → impact → question. Probe without interrogating, then close the decision loop.",
      ),
      option(
        "B",
        "Ask Vincent to list every agent pain point, then vote with the workshop participants.",
        "Inclusive but shallow",
        0,
        { collaboration: 3, analysis: -3, impact: -2 },
        "The group produces a long list and votes for familiar topics, but the result is not tied to value, risk, or feasibility.",
        "You created participation and gathered broad frontline input.",
        "Popularity does not establish root cause, business value, or the accountable decision owner.",
        "Use the list as input, then compare options against outcome, evidence, risk, dependency, and reversibility.",
        "Workshops should produce a decision or commitment, not only more information.",
      ),
      option(
        "C",
        "Ask rapid-fire detailed questions so Vincent has less room to go off topic.",
        "Efficient but interrogative",
        -3,
        { collaboration: -5, analysis: 1 },
        "You collect facts, but Vincent becomes defensive and stops sharing the exceptions that matter most.",
        "You recognized the need for specificity and protected limited workshop time.",
        "The questioning style reduced psychological safety and treated the SME as a data source rather than a reasoning partner.",
        "Explain why each question matters, reflect what you heard, and invite correction before probing deeper.",
        "A senior BA probes evidence without making the other person feel cross-examined.",
      ),
      option(
        "D",
        "Let Andrea choose the use case because the workshop cannot reach consensus.",
        "Escalation without a decision package",
        -5,
        { ownership: -6, collaboration: -2 },
        "Andrea can choose, but she asks why the BA team did not present evidence, options, and a recommendation.",
        "You correctly recognized that the Product Owner has final scope authority.",
        "Escalation should resolve a decision the team cannot own, not replace analysis and facilitation.",
        "Bring Andrea a compact package: outcome, evidence, options, trade-offs, recommendation, and required decision.",
        "Escalate decisions, not raw problems.",
      ),
    ],
  },
  {
    id: 8,
    phase: "Frame the work",
    timeline: "Month 2 · Scope conflict",
    title: "Everyone is right",
    speaker: "Andrea · Senior Product Owner",
    manager: "Andrea",
    scenario:
      "Agents want bilingual answers to every question. Operations wants personal performance and policy status. Compliance prohibits unapproved advice and uncontrolled personal data. IT says authorized APIs will take more than eight weeks, while management wants visible adoption this quarter. Andrea asks you for the recommended MVP.",
    question: "What do you recommend?",
    hint:
      "Separate needs, requirements, constraints, preferences, and assumptions. Do not average the requests; present viable options and name the decision rights.",
    source: "Enterprise Stakeholder Management",
    options: [
      option(
        "A",
        "Recommend a phased hybrid: approved bilingual knowledge with citations now, authenticated personal-data APIs later, and controlled transactions only after controls are proven.",
        "Strong product judgment",
        8,
        { analysis: 5, risk: 6, ownership: 6, impact: 5 },
        "Andrea approves Phase 1 and records Compliance and Security control authority. The roadmap preserves value without pretending dependencies do not exist.",
        "You reconciled competing truths into a feasible sequence and made the control boundary explicit.",
        "Position the knowledge-only phase honestly so users do not expect personal answers.",
        "Document scope, non-scope, decision rationale, success criteria, and the evidence required to unlock each later phase.",
        "A phased option can preserve early learning and safe expansion when value, risk, and dependencies mature at different speeds.",
      ),
      option(
        "B",
        "Launch a broad chatbot and hide unsupported personal features behind a beta label.",
        "High-risk compromise",
        -8,
        { risk: -9, reliability: -5, impact: -2 },
        "The beta label does not solve authorization or advice risk. Grace blocks the release and the date is lost.",
        "You tried to retain broad user value and signal that the product was still learning.",
        "A label cannot replace identity, authorization, deterministic rules, audit, or approved content.",
        "Reduce scope to safe capabilities and create explicit technical and control gates for expansion.",
        "Risk controls change system behavior. They are not disclaimers added after the design.",
      ),
      option(
        "C",
        "Deliver only a knowledge bot with no roadmap because it is the safest option within eight weeks.",
        "Safe but strategically incomplete",
        2,
        { risk: 5, reliability: 2, impact: -3, ownership: -1 },
        "The release is controlled, but agents see limited value and management questions whether the team understood the bigger need.",
        "You respected feasibility, timeline, and the need for approved sources.",
        "You treated today’s constraint as a permanent product boundary and did not address the higher-value journey.",
        "Pair the safe MVP with a credible expansion roadmap, dependencies, and decision gates.",
        "A bounded v1 should be honest about limits while preserving the path to the outcome users actually need.",
      ),
      option(
        "D",
        "Ask every stakeholder to compromise until all requests fit into a reduced version.",
        "Consensus trap",
        -3,
        { collaboration: 1, ownership: -5, analysis: -3 },
        "The compromise produces unclear scope: too broad for controls and too shallow for user value.",
        "You tried to respect every stakeholder’s legitimate objective.",
        "Some constraints cannot be averaged, and product decisions require explicit trade-offs and accountable ownership.",
        "Present distinct options with value, risk, effort, dependency, and reversibility; recommend one and ask Andrea to decide.",
        "Alignment is not making everyone equally happy. It is making the trade-off explicit enough to commit.",
      ),
    ],
  },
  {
    id: 9,
    phase: "Frame the work",
    timeline: "Month 2 · Refinement",
    title: "Make the decision buildable",
    speaker: "Ravi · Developer",
    manager: "Maya",
    scenario:
      "The team approves the knowledge-assistant MVP. Ravi receives a story saying, “As an agent, I want accurate bilingual answers so I can serve customers faster.” He asks what happens for outdated sources, mixed-language questions, two intents in one message, missing evidence, and advice-seeking questions.",
    question: "What requirement package do you create?",
    hint:
      "Connect outcome to process and rules, then to requirements, acceptance criteria, tests, and evidence. Include exceptions and non-scope.",
    source: "Business Analysis Delivery Lifecycle",
    options: [
      option(
        "A",
        "Create a TO-BE flow, rule and exception table, source/ownership rules, non-scope, NFRs, and traceable scenario-based acceptance criteria.",
        "Strong BA craft",
        7,
        { analysis: 7, reliability: 4, risk: 3 },
        "Ravi and Chloe can refine and test the story without inventing product behavior. Rework falls during the sprint.",
        "You translated the decision into buildable, testable behavior including failure paths.",
        "Keep artifacts connected and owned; a large documentation set can become stale quickly.",
        "Maintain one trace: outcome → rule/process → requirement → acceptance criterion → test → evidence.",
        "Artifacts exist to support decisions, reduce ambiguity, and leave necessary traceability—not to prove effort.",
      ),
      option(
        "B",
        "Expand the user story into a long description and let QA define the edge cases during testing.",
        "Readable but late",
        -3,
        { analysis: -4, reliability: -3, collaboration: -1 },
        "QA discovers unresolved behavior after development, and several findings become requirement gaps rather than defects.",
        "You improved context and recognized QA’s expertise in scenario design.",
        "Business rules and expected exception behavior are product decisions, not details to discover after coding.",
        "Co-create edge cases with QA and Engineering during refinement, then encode expected outcomes before build.",
        "BA work continues through delivery, but ambiguity should move left whenever it changes design.",
      ),
      option(
        "C",
        "Write separate stories for every possible edge case so nothing is missed.",
        "Thorough but unmanageable",
        0,
        { analysis: 2, reliability: -2, ownership: -1 },
        "The backlog becomes fragmented and relationships between rules are hard to see. Refinement slows down.",
        "You took exception handling seriously and tried to make coverage visible.",
        "Not every scenario needs a separate story; excessive decomposition can hide the underlying rule model.",
        "Group behavior by rule and workflow, then express representative happy, negative, boundary, and fallback criteria.",
        "Choose the artifact that makes the decision clearest, not the artifact that creates the most tickets.",
      ),
      option(
        "D",
        "Tell Ravi to implement the happy path first and ask questions during the sprint because the deadline is tight.",
        "Fast start, expensive ambiguity",
        -6,
        { reliability: -6, analysis: -5, risk: -3 },
        "The happy path works, but the architecture cannot support safe fallback without rework. The deadline becomes less certain.",
        "You protected momentum and acknowledged that teams learn during delivery.",
        "You deferred known decision-critical ambiguity rather than sequencing work around it.",
        "Resolve control boundaries and architecture-changing exceptions now; defer only low-impact detail with an owner and date.",
        "Speed comes from reducing expensive uncertainty early, not simply starting code sooner.",
      ),
    ],
  },
  {
    id: 10,
    phase: "Build safe AI",
    timeline: "Month 3 · Design review",
    title: "Can it see my policy?",
    speaker: "Iris · AI Engineer",
    manager: "Andrea",
    scenario:
      "A pilot agent asks the assistant, “Show me customer Chan’s policy status and calculate the premium due.” Iris says the LLM can probably answer if customer records are indexed alongside product documents. Grace asks you to define the correct routing and control boundary before design continues.",
    question: "Which design do you support?",
    hint:
      "Approved knowledge, personal data, calculations, and transactions require different routes. The LLM may explain grounded results but must not grant access or invent official values.",
    source: "AIA Automation CoE Interview Prep Pack",
    options: [
      option(
        "A",
        "Authenticate and authorize first; fetch policy data through an approved API; calculate deterministically; let the LLM explain only the grounded result; log access.",
        "Strong control design",
        8,
        { risk: 8, analysis: 5, ownership: 4 },
        "Grace approves the boundary for further design. Iris separates conversational explanation from trusted data and calculation services.",
        "You matched each task to its correct source of truth and protected entitlement and auditability.",
        "Specify minimum necessary fields and safe behavior for denied access, missing data, and backend failure.",
        "Document route, source of truth, authorization, deterministic logic, response checks, fallback, and logging.",
        "Use the LLM for language and explanation; use controlled systems for identity, data, calculations, and decisions.",
      ),
      option(
        "B",
        "Index customer records in RAG but filter results using the agent’s login ID.",
        "Severe privacy design failure",
        -10,
        { risk: -12, reliability: -6, analysis: -4 },
        "Grace stops the design. The proposed retrieval layer cannot reliably enforce customer-policy entitlement or minimum data exposure.",
        "You recognized that user identity must affect access to personal information.",
        "A simple retrieval filter is not an adequate authorization, entitlement, calculation, or audit control for official policy data.",
        "Keep personal records out of general knowledge retrieval; use an authorized backend API and deterministic functions.",
        "Personalized enquiry is a controlled data workflow, not a richer knowledge-search problem.",
        { severeFlag: "privacy" },
      ),
      option(
        "C",
        "Refuse all personal-data questions permanently and keep the product knowledge-only.",
        "Safe but overly restrictive",
        1,
        { risk: 5, impact: -5, ownership: -1 },
        "The immediate release remains safe, but the team loses a high-value path that could be supported through controlled integration.",
        "You refused to let timeline pressure weaken privacy controls.",
        "You turned a current dependency into a permanent product limitation instead of designing a safe future route.",
        "Keep personal data out of the MVP while defining the authorization, API, logging, and control requirements for a later phase.",
        "Safe scope now and a controlled roadmap later can both be true.",
      ),
      option(
        "D",
        "Let the LLM answer but show a disclaimer that policy data may be inaccurate.",
        "Severe source-of-truth failure",
        -10,
        { risk: -12, reliability: -8 },
        "Andrea rejects the proposal. A disclaimer does not make unauthorized or inaccurate policy information acceptable.",
        "You attempted to communicate uncertainty to the user.",
        "Official personal data and calculations require accuracy, authorization, and audit controls; uncertainty messaging cannot replace them.",
        "Use the policy backend as source of truth and refuse safely when evidence or access is unavailable.",
        "Disclaimers describe limits. They do not create missing controls.",
        { severeFlag: "personal-data-source" },
      ),
    ],
  },
  {
    id: 11,
    phase: "Build safe AI",
    timeline: "Month 3 · Quality planning",
    title: "Always accurate",
    speaker: "Andrea · Senior Product Owner",
    manager: "Andrea",
    scenario:
      "A steering-committee slide says the assistant must be “100% accurate.” Iris says no probabilistic system can guarantee that across every input. Chloe needs acceptance criteria, while Andrea wants a quality statement that business and Compliance can understand without sounding evasive.",
    question: "How do you redefine acceptance?",
    hint:
      "Replace absolute promises with representative coverage, thresholds, critical-error limits, safe fallback behavior, and named ownership.",
    source: "Career Roadmap · AI acceptance criteria",
    options: [
      option(
        "A",
        "Define a representative golden set, quality thresholds by risk class, zero tolerance for critical errors, no-answer behavior, and production monitoring owners.",
        "Strong AI BA craft",
        8,
        { analysis: 7, risk: 6, impact: 3 },
        "The committee sees a testable quality contract rather than a vague retreat from accuracy. Chloe can trace requirements to tests.",
        "You made probabilistic quality measurable while keeping severe risk non-negotiable.",
        "Explain sampling limits and how the golden set will stay representative as queries and content change.",
        "State coverage, metric definitions, thresholds, critical-error policy, fallback, review cadence, and owners.",
        "AI acceptance is not one pass/fail promise. It is thresholds plus confidence, critical boundaries, and operational response.",
      ),
      option(
        "B",
        "Keep 100% as an aspirational target and let QA decide whether the observed results are acceptable.",
        "Comforting but untestable",
        -5,
        { reliability: -5, analysis: -5, risk: -2 },
        "QA cannot determine exit criteria consistently, and stakeholders interpret the same result differently.",
        "You preserved the ambition for high quality and involved QA in evidence review.",
        "An aspiration is not an acceptance contract, and QA should not invent business risk tolerance.",
        "Agree metrics and thresholds with Product, Business, QA, and control owners before execution.",
        "A target must tell the team what evidence is enough to launch, stop, or improve.",
      ),
      option(
        "C",
        "Use average answer accuracy above 90% as the single acceptance criterion.",
        "Measurable but dangerously coarse",
        -2,
        { analysis: 1, risk: -5 },
        "The average hides a small number of high-impact advice and privacy failures. Grace rejects the scorecard.",
        "You replaced an absolute promise with a measurable threshold.",
        "One average treats harmless wording issues and critical control failures as interchangeable.",
        "Segment by use case and risk; add critical-error rate, grounding, refusal, access, tool, and journey measures.",
        "Separate failure signals so each has a defined response.",
      ),
      option(
        "D",
        "Avoid numerical criteria because users care about trust and satisfaction more than technical metrics.",
        "User-aware but non-governable",
        -4,
        { impact: 1, analysis: -6, reliability: -3 },
        "The team collects feedback but cannot establish release readiness or diagnose specific failure layers.",
        "You recognized that perceived trust and task completion matter beyond technical accuracy.",
        "Experience measures complement rather than replace retrieval, grounding, tool, security, and operational evidence.",
        "Use a scorecard linking system quality to task completion, trust, escalation, and business outcome.",
        "Quality is a stack: routing, retrieval, tools, grounding, security, experience, and operations.",
      ),
    ],
  },
  {
    id: 12,
    phase: "Build safe AI",
    timeline: "Month 4 · Incident review",
    title: "The accuracy drop",
    speaker: "Iris · AI Engineer",
    manager: "Maya",
    scenario:
      "After a knowledge-base update, answer accuracy falls by eight points. Several people propose rewriting prompts immediately. The failed cases include missing source chunks, outdated documents, wrong intent routing, unsupported claims, and one calculation mismatch. Maya asks you to lead the diagnosis.",
    question: "What do you do?",
    hint:
      "Classify failures by layer before choosing a fix. Different causes require different owners and responses.",
    source: "Career Roadmap · Failure taxonomy",
    options: [
      option(
        "A",
        "Build a failure taxonomy, label representative cases, quantify each category, assign owners, and retest the highest-risk root causes first.",
        "Strong diagnostic ownership",
        7,
        { analysis: 7, ownership: 5, reliability: 3 },
        "The team finds that metadata changes caused most retrieval misses, while the calculation issue belongs to a separate tool path.",
        "You prevented one visible symptom from triggering a one-size-fits-all fix.",
        "Keep the taxonomy actionable and stable enough to compare releases; avoid categories so detailed that reviewers disagree constantly.",
        "Separate intent, retrieval, source freshness, grounding, prompt, tool, security, and experience failures; link each to an owner and response.",
        "Failure taxonomy turns “the bot is wrong” into diagnosable system behavior.",
      ),
      option(
        "B",
        "Rewrite the system prompt first because it is the fastest lever and often improves answer behavior.",
        "Fast but layer-blind",
        -4,
        { analysis: -6, reliability: -2 },
        "Wording improves on a few cases, but retrieval misses and stale sources remain. The retest produces noisy results.",
        "You looked for a reversible, low-effort intervention.",
        "Prompt changes cannot retrieve missing evidence, update stale knowledge, or correct deterministic calculations.",
        "Classify failures first, then change the smallest component responsible for the dominant category.",
        "Fix the failure layer, not the most familiar AI component.",
      ),
      option(
        "C",
        "Roll back the entire knowledge-base update immediately and investigate later.",
        "Safe containment, incomplete diagnosis",
        2,
        { reliability: 4, risk: 2, analysis: -2 },
        "Quality recovers quickly, but the team still does not know which update was harmful or how to prevent recurrence.",
        "You prioritized service stability and chose a reversible containment action.",
        "Rollback is containment, not root-cause analysis, and may also restore outdated information.",
        "Contain the incident, preserve evidence, classify failures, then reintroduce validated changes in controlled slices.",
        "Operational response separates stabilize, diagnose, correct, and prevent.",
      ),
      option(
        "D",
        "Hide the temporary drop from senior stakeholders until the team has a fix to avoid unnecessary concern.",
        "Hidden-risk failure",
        -9,
        { reliability: -10, risk: -7, ownership: -3 },
        "Andrea learns about the issue from pilot users. The technical problem becomes a trust problem with the project team.",
        "You wanted to avoid noise before having a useful recommendation.",
        "Known material risk should not arrive as a late surprise; waiting removes leaders’ ability to change scope or timing.",
        "Report outcome, current impact, containment, investigation plan, next checkpoint, and any decision needed.",
        "Reliable escalation brings a decision package early enough to act.",
        { severeFlag: "hidden-critical-risk" },
      ),
    ],
  },
  {
    id: 13,
    phase: "Build safe AI",
    timeline: "Month 5 · Expansion proposal",
    title: "The e-claim shortcut",
    speaker: "Elaine · Business Unit Stakeholder",
    manager: "Andrea",
    scenario:
      "Elaine wants the assistant to submit simple e-claims before quarter end. She proposes letting the LLM decide whether evidence looks complete, infer missing fields from conversation history, and send the claim automatically to reduce clicks. Andrea asks you to define a safe yet useful workflow.",
    question: "What workflow do you recommend?",
    hint:
      "The AI may guide and extract, but identity, entitlement, required fields, eligibility, confirmation, submission, and claim decisions need controlled systems.",
    source: "E-Claim Model Workflow",
    options: [
      option(
        "A",
        "Use AI to guide and extract; apply deterministic validations; show a structured summary; require confirmation; submit via the claims API; log and hand off exceptions.",
        "Strong controlled workflow",
        9,
        { risk: 8, analysis: 5, impact: 5, ownership: 4 },
        "The team keeps conversational convenience while preserving authoritative checks, confirmation, audit, and human judgment.",
        "You placed AI inside a governed workflow rather than letting it become the decision system.",
        "Add duplicate-submission protection, timeout recovery, and clear ownership for inconsistent evidence.",
        "Define every control boundary and failure path from authentication through backend reference and next steps.",
        "AI assists; controlled systems validate and execute; humans handle judgment-heavy exceptions.",
      ),
      option(
        "B",
        "Allow automatic submission for low-value claims and audit a sample afterward.",
        "Severe transaction-control failure",
        -10,
        { risk: -12, reliability: -7 },
        "Grace blocks the proposal because monetary value does not remove entitlement, evidence, confirmation, fraud, and duplicate-submission risks.",
        "You tried to match control effort to claim value and reduce user friction.",
        "Post-hoc sampling cannot undo unauthorized, duplicate, incomplete, or wrongly submitted transactions.",
        "Keep explicit confirmation and deterministic checks for every submission; vary review intensity only within approved policy.",
        "Transactional AI needs prevention and audit, not audit alone.",
        { severeFlag: "unsafe-transaction" },
      ),
      option(
        "C",
        "Keep the assistant informational and send users to the existing claim form for every case.",
        "Safe but low-value",
        1,
        { risk: 5, impact: -5, ownership: -1 },
        "The release carries little new risk but does not remove the workflow friction that justified the expansion.",
        "You protected the current claims source of truth and avoided over-automation.",
        "You assumed the only safe choices were full automation or no workflow assistance.",
        "Add guided collection, document extraction, missing-item checks, and a reviewed handoff even before direct submission is ready.",
        "Controlled augmentation can create value before end-to-end automation is justified.",
      ),
      option(
        "D",
        "Let the LLM infer missing information but require the user to approve the final summary.",
        "Confirmation overconfidence",
        -7,
        { risk: -9, analysis: -3 },
        "Users approve plausible-looking inferred fields without noticing errors. The confirmation step creates false confidence.",
        "You included user confirmation and tried to reduce repeated questions.",
        "Confirmation is not permission to invent missing facts, especially in a regulated transaction.",
        "Ask for missing required fields explicitly, label extracted evidence, and block submission until deterministic validation passes.",
        "A confirmation screen verifies supplied facts; it does not legitimize fabricated ones.",
      ),
    ],
  },
  {
    id: 14,
    phase: "Deliver real adoption",
    timeline: "Month 6 · UAT week",
    title: "Almost ready",
    speaker: "Chloe · QA Lead",
    manager: "Maya",
    scenario:
      "The happy-path UAT scenarios pass, and the launch date is close. Remaining scenarios cover unauthorized users, mixed Cantonese-English questions, stale sources, API timeouts, duplicate submissions, prompt attacks, and audit logs. Elaine suggests signing off now and treating the rest as post-launch QA.",
    question: "How do you handle sign-off?",
    hint:
      "UAT proves business acceptance across realistic scenarios and controls. Define exit criteria and make residual risk visible to accountable owners.",
    source: "Business Analysis Delivery Lifecycle · UAT",
    options: [
      option(
        "A",
        "Keep risk-based critical scenarios in UAT, triage defects versus gaps and changes, document residual risk, and obtain business plus control-owner sign-off.",
        "Strong delivery judgment",
        8,
        { reliability: 6, risk: 7, collaboration: 3 },
        "The team fixes an authorization defect before launch and consciously defers two low-risk language variants.",
        "You protected the launch without pretending every open item had equal severity.",
        "Use explicit exit criteria so UAT does not become an endless search for perfection.",
        "Trace critical rules and exceptions to tests, classify findings, recommend disposition, and name who accepts residual risk.",
        "UAT is business evidence for release readiness, not casual exploratory testing or a second system-test phase.",
      ),
      option(
        "B",
        "Sign off because QA already tested the system and UAT should focus only on whether users like the happy path.",
        "Misunderstood UAT",
        -7,
        { risk: -8, reliability: -6, analysis: -3 },
        "An unauthorized-access issue reaches the pilot and forces an emergency suspension.",
        "You distinguished technical QA from user-facing acceptance and protected the date.",
        "Business acceptance includes permissions, exceptions, controls, operational handling, and fallback—not only preference.",
        "Use end-to-end business scenarios derived from rules, risks, and acceptance criteria.",
        "A system can function technically and still be unacceptable operationally or from a control perspective.",
      ),
      option(
        "C",
        "Delay launch until every UAT scenario passes with zero defects of any severity.",
        "Safe but absolute",
        -2,
        { risk: 4, reliability: -3, impact: -3 },
        "The team removes all defects but loses the pilot window over two low-impact wording issues.",
        "You treated UAT findings seriously and avoided normalizing known defects.",
        "Zero-defect rules ignore severity, workaround, residual risk, and the cost of delay.",
        "Set risk-based exit criteria and ask accountable owners to accept only explicit, bounded residual risk.",
        "Quality decisions compare customer, regulatory, financial, and operational impact—not just defect counts.",
      ),
      option(
        "D",
        "Let Elaine sign off alone because the business owns the product outcome.",
        "Incomplete decision rights",
        -5,
        { collaboration: -2, risk: -7, ownership: -2 },
        "Business accepts the experience, but Compliance and Operations have not accepted control and support readiness.",
        "You correctly identified the accountable business owner’s role in acceptance.",
        "Business ownership does not replace required control, security, operations, and technical sign-offs.",
        "Create a sign-off map showing who accepts product behavior, controls, support readiness, and residual risk.",
        "Decision rights can be shared by domain: product scope, control approval, and operational readiness are not identical.",
      ),
    ],
  },
  {
    id: 15,
    phase: "Deliver real adoption",
    timeline: "Month 7 · Pilot review",
    title: "Nobody is using it",
    speaker: "Vincent · Agency Operations SME",
    manager: "Andrea",
    scenario:
      "Pilot login numbers are low. Elaine wants mandatory training, while Vincent says agents do not trust the assistant after seeing one outdated answer. Usage data also shows login failures in one district and high abandonment after clarification prompts. Andrea asks you to recommend the next intervention.",
    question: "What do you do first?",
    hint:
      "Low adoption is not one problem. Diagnose awareness, access, capability, trust, and workflow/product friction using segmented evidence.",
    source: "Adoption Model Answer",
    options: [
      option(
        "A",
        "Define meaningful adoption, segment the funnel, interview users and non-users, classify causes, then match interventions to access, trust, skill, or friction.",
        "Strong adoption judgment",
        8,
        { impact: 7, analysis: 6, collaboration: 4 },
        "The team fixes district access, removes a poor clarification loop, and publishes source freshness indicators before targeted training.",
        "You treated adoption as repeated workflow behavior and matched solutions to distinct causes.",
        "Move quickly on obvious access failures while the fuller diagnosis continues.",
        "Track eligible activation, repeat use, core-task completion, resolution, satisfaction, support demand, and quality guardrails.",
        "Training solves capability gaps. It cannot repair access, product friction, or broken trust.",
      ),
      option(
        "B",
        "Run mandatory training for all agents because awareness and confidence usually drive early adoption.",
        "Plausible but one-size-fits-all",
        -3,
        { collaboration: 1, impact: -5, analysis: -3 },
        "Attendance rises but repeat usage remains low because login and product-quality issues persist.",
        "You proposed a concrete intervention and recognized that confidence can affect adoption.",
        "You prescribed training before distinguishing awareness, access, capability, trust, and workflow friction.",
        "Use training only for the segments whose behavior and interviews show a capability gap.",
        "Intervention should follow diagnosis; otherwise activity can rise while the product outcome stays flat.",
      ),
      option(
        "C",
        "Add incentives for logins so management can see adoption improving this month.",
        "Metric gaming",
        -6,
        { impact: -8, reliability: -3, ownership: -2 },
        "Login counts jump, but core-task completion and repeat use do not. The metric loses credibility with Andrea.",
        "You responded to urgency and looked for a lever that could change user behavior quickly.",
        "Login is an activity metric. Incentivizing it can hide whether the assistant solves a real task.",
        "Define adoption as repeated completion of a valuable workflow with acceptable quality and risk.",
        "Measure the behavior that represents value, not the easiest number to move.",
      ),
      option(
        "D",
        "Conclude that agents resist change and ask district managers to enforce usage.",
        "Blame-based diagnosis",
        -7,
        { collaboration: -8, analysis: -5, impact: -4 },
        "Agents comply briefly but share more negative stories. The team loses the chance to learn from real access and trust failures.",
        "You recognized that local leaders influence frontline behavior.",
        "You treated resistance as a user trait rather than evidence about access, trust, workflow, or product quality.",
        "Turn resistance into requirements: ask what cost, risk, or experience makes the old behavior rational.",
        "User resistance often contains process knowledge. Diagnose it before escalating pressure.",
      ),
    ],
  },
  {
    id: 16,
    phase: "Deliver real adoption",
    timeline: "Month 8 · Steering update",
    title: "Six weeks of new scope",
    speaker: "Andrea · Senior Product Owner",
    manager: "Andrea",
    scenario:
      "A senior sponsor asks for voice input and an additional language before the planned October pilot. Ravi estimates that both additions will delay launch by six weeks and expand privacy testing. Andrea asks you to draft the steering update and recommendation for tomorrow morning.",
    question: "What message do you prepare?",
    hint:
      "Executive communication needs outcome, status, risk and consequence, recommendation, and the required decision—with explicit scope/date trade-offs.",
    source: "Enterprise Stakeholder Management",
    options: [
      option(
        "A",
        "Show the pilot outcome, current status, six-week impact and privacy work, then recommend keeping October with one bounded addition or moving both to November.",
        "Strong executive communication",
        8,
        { reliability: 6, ownership: 6, impact: 5, collaboration: 3 },
        "The sponsor chooses the October option with one addition. The rationale and deferred scope are recorded.",
        "You turned a senior request into a decision with visible consequences and a clear recommendation.",
        "Pre-wire the sponsor before the meeting so the trade-off does not feel like a public rejection.",
        "Lead with outcome, then status, risk/impact, recommendation, and the exact decision needed by when.",
        "Constructive challenge protects the sponsor’s intended outcome while making cost and risk explicit.",
      ),
      option(
        "B",
        "Add both requests and ask the team to work harder because senior sponsorship is important for conversion and funding.",
        "Unsustainable agreement",
        -8,
        { reliability: -8, collaboration: -4, risk: -4 },
        "The team burns time, misses October anyway, and discovers privacy work too late. Your commitment becomes the visible failure.",
        "You understood the strategic importance of sponsorship and tried to protect the relationship.",
        "You accepted a trade-off on behalf of delivery and control teams without evidence that the date was achievable.",
        "Present the sponsor with options that preserve the desired adoption outcome under realistic scope, time, and control constraints.",
        "Managing upward means preventing late surprise, not shielding leaders from trade-offs.",
      ),
      option(
        "C",
        "Report that the team is assessing feasibility and will provide a recommendation after more technical analysis.",
        "Careful but non-decisive",
        -3,
        { analysis: 1, ownership: -5, reliability: -2 },
        "The steering meeting passes without a scope decision, compressing the remaining time further.",
        "You avoided giving an unsupported estimate and recognized technical uncertainty.",
        "The available estimate is already enough to frame options; delaying the decision has a cost.",
        "State confidence and remaining uncertainty, recommend a reversible path, and name when unresolved facts will be confirmed.",
        "Use confidence levels instead of false certainty or indefinite analysis.",
      ),
      option(
        "D",
        "Tell the sponsor the request is out of scope and cannot be considered until after launch.",
        "Clear boundary, weak influence",
        -2,
        { reliability: 2, collaboration: -5, ownership: -1 },
        "The scope stays stable, but the sponsor feels the team ignored the adoption objective behind the request.",
        "You protected the committed date and avoided silent scope expansion.",
        "A hard boundary without options or outcome framing can sound procedural rather than product-minded.",
        "Acknowledge the intended adoption value, show the trade-off, and recommend the best sequence.",
        "Scope is a trade-off mechanism, not a wall that ends the conversation.",
      ),
    ],
  },
  {
    id: 17,
    phase: "Earn trust & ownership",
    timeline: "Month 9 · Quarterly review",
    title: "Make the work visible",
    speaker: "Maya · Assistant Manager",
    manager: "Maya",
    scenario:
      "Your evaluation changes improved grounded-answer accuracy and reduced repeated enquiries, but most senior leaders only see weekly task lists. Maya asks you to prepare a short update for Andrea. Ken contributed important review rules, and Iris fixed the retrieval pipeline that enabled the improvement.",
    question: "How do you present your contribution?",
    hint:
      "Translate delivery quality into business impact, show the reusable method, credit collaborators, and make the next decision clear.",
    source: "Career Roadmap · quantified wins and ownership creep",
    options: [
      option(
        "A",
        "Show baseline to outcome, business implication, the reusable evaluation method, team contributions, remaining risk, and the next recommendation.",
        "Strong ownership signal",
        9,
        { impact: 8, ownership: 7, collaboration: 4, reliability: 3 },
        "Andrea sees both measurable value and a method the team can reuse. She asks you to lead evaluation design for the next use case.",
        "You made impact legible without erasing collaborators and connected the win to a next decision.",
        "Avoid overstating causality if several changes happened at once; label estimates and assumptions.",
        "Use a compact story: baseline, intervention, measured change, business meaning, method, team, risk, next decision.",
        "BA execution becomes Senior BA ownership when you define how good work is done and make the method reusable.",
      ),
      option(
        "B",
        "Send a detailed list of every task completed so leaders can see how much work the team handled.",
        "Visible activity, weak outcome",
        -2,
        { reliability: 2, impact: -5, ownership: -2 },
        "Andrea appreciates the effort but cannot tell what changed for agents or which capability deserves more investment.",
        "You documented delivery thoroughly and made team effort visible.",
        "Task volume does not explain value, quality improvement, risk reduction, or the decision leadership should make.",
        "Group activities under the outcome they changed and quantify the result against a baseline.",
        "Senior audiences need outcome, evidence, risk, recommendation, and decision—not a work diary.",
      ),
      option(
        "C",
        "Present the result as your personal framework so Andrea sees that you are difficult to replace.",
        "Visible but trust-eroding",
        -5,
        { ownership: 2, collaboration: -8, reliability: -3 },
        "Andrea notices that Ken and Iris are missing from the story. Your visibility improves briefly while team trust falls.",
        "You recognized that reusable methods and visible ownership matter for career progression.",
        "Claiming shared work as personal weakens the relationships and credibility that make future ownership possible.",
        "Be precise about what you designed, what others contributed, and what the team achieved together.",
        "Relational luck compounds through useful, generous collaboration—not by hoarding credit.",
      ),
      option(
        "D",
        "Let Maya present the work because managers should communicate upward and self-promotion can look political.",
        "Humble but invisible",
        -4,
        { collaboration: 1, ownership: -6, impact: -3 },
        "The result is mentioned, but Andrea does not learn how you reasoned or whether you can represent the work independently.",
        "You respected your manager’s role and avoided taking sole credit.",
        "Avoiding all upward communication prevents leaders from observing the judgment required for larger ownership.",
        "Co-author the update with Maya and present the part you owned, with clear team attribution.",
        "Upward management means leaders can explain your work and trust you to explain it—not constant self-promotion.",
      ),
    ],
  },
  {
    id: 18,
    phase: "Earn trust & ownership",
    timeline: "Month 9–12 · Career checkpoint",
    title: "The contract conversation",
    speaker: "Maya · Assistant Manager",
    manager: "Maya",
    scenario:
      "Your one-year contract has three months remaining. The project continues, but headcount and conversion timing are unclear. You have a record of delivery quality, one quantified win, a reusable evaluation method, stakeholder feedback, and two capability gaps you are still addressing. Maya has not started a renewal conversation.",
    question: "How do you approach the checkpoint?",
    hint:
      "Ask early enough to act. Bring evidence, request a clear performance assessment and decision timeline, surface gaps, and keep a professional fallback plan.",
    source: "Career Roadmap · contract conversion",
    options: [
      option(
        "A",
        "Book a direct checkpoint: present evidence, ask whether you are on track for permanent conversion, request gaps and decision timing, and agree next proof points.",
        "Strong career agency",
        10,
        { ownership: 8, reliability: 6, impact: 4, collaboration: 3 },
        "Maya gives specific feedback and starts the conversion case with time to close two remaining gaps.",
        "You made the decision discussable early, used evidence rather than entitlement, and invited actionable correction.",
        "Keep the tone focused on contribution and fit; do not make your manager guess at an ultimatum.",
        "Ask: “Against the standard for conversion, am I on track? What evidence is missing, who decides, and when should we review?”",
        "The midpoint and pre-renewal conversations create time to change the outcome. Waiting removes options.",
      ),
      option(
        "B",
        "Ask for a renewal and permanent conversion, present your evidence, and quietly benchmark external options as a professional fallback.",
        "Strong with a broader BATNA",
        7,
        { ownership: 7, impact: 3, reliability: 3 },
        "Maya understands your preference and the evidence supporting it. You preserve options without threatening the relationship.",
        "You combined internal commitment with realistic career risk management.",
        "Lead with the performance standard and decision timeline; an early external benchmark should not distract from current delivery.",
        "Treat external awareness as a fallback, not leverage to manufacture urgency before the internal process is clear.",
        "Stay is a strategy, not a trap. Monitor controllable performance and uncontrollable organizational signals separately.",
      ),
      option(
        "C",
        "Wait until Maya raises the topic because asking early could make you look insecure or disloyal.",
        "Too passive",
        -8,
        { ownership: -9, reliability: -3 },
        "The decision starts late, and there is little time to correct gaps or resolve headcount. Your outcome depends mostly on existing momentum.",
        "You wanted to respect the process and avoid creating unnecessary pressure.",
        "Silence does not demonstrate loyalty; it removes time for feedback, sponsorship, and operational planning.",
        "Request a normal performance and contract-planning checkpoint before the final quarter.",
        "Career agency is an operating skill: surface the decision early enough for both sides to act responsibly.",
      ),
      option(
        "D",
        "Tell Maya you need a permanent offer within two weeks or you will leave.",
        "Premature ultimatum",
        -9,
        { collaboration: -8, reliability: -4, ownership: -2 },
        "Maya cannot meet the artificial deadline and now questions whether you intend to finish the contract professionally.",
        "You made your preference clear and refused indefinite ambiguity.",
        "The ultimatum ignores decision authority, budget timing, and the evidence-based conversation that could build sponsorship.",
        "Ask for the decision process and credible timing, state your preference, and set personal fallback milestones privately.",
        "Negotiation is strongest when options, evidence, decision rights, and timing are clear—not when urgency is manufactured.",
      ),
    ],
  },
];
